const DATA = [
 {
  "src": "The Verge AI",
  "dom": "ai",
  "zh": "AMD以超80亿美元收购AI公司World Labs",
  "en": "AMD is acquiring AI company World Labs in a deal worth more than $8 billion",
  "sum": "AMD宣布以约82亿美元全股票交易收购李飞飞联合创办的AI研究实验室World Labs。",
  "t": "05:31",
  "heat": 9.0,
  "ext": true,
  "chars": 756,
  "preview": "World Labs co-founder and CEO Fei-Fei Li. | Bloomberg via Getty Images AMD announced today that it's acquiring World Labs, an AI research lab co-founded by the ",
  "url": "https://www.theverge.com/tech/1001749/amd-world-labs-ai-acquisition-deal"
 },
 {
  "src": "TechCrunch AI",
  "dom": "ai",
  "zh": "AMD将以82亿美元收购李飞飞的World Labs",
  "en": "AMD will acquire Fei-Fei Li’s World Labs for $8.2 billion",
  "sum": "收购完成后，World Labs创始人李飞飞将加入AMD任执行副总裁兼首席科学家。",
  "t": "04:39",
  "heat": 9.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://techcrunch.com/2026/09/28/amd-will-acquire-fei-fei-lis-world-labs-for-8-2-billion/"
 },
 {
  "src": "量子位",
  "dom": "ai",
  "zh": "李飞飞创业公司被苏姿丰550亿收购！世界模型最大交易落地",
  "en": "",
  "sum": "李飞飞将入职AMD首席科学家",
  "t": "08:49",
  "heat": 9.0,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://www.qbitai.com/2026/09/499098.html"
 },
 {
  "src": "Solidot",
  "dom": "ai",
  "zh": "AMD以82亿美元收购李飞飞的World Labs",
  "en": "AMD 以 82 亿美元收购李飞飞的 World Labs",
  "sum": "AMD宣布以约82亿美元全股票收购李飞飞创办的World Labs，李飞飞将出任AMD执行副总裁兼首席科学家。",
  "t": "16:19",
  "heat": 9.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://www.solidot.org/story?sid=85501"
 },
 {
  "src": "开源中国",
  "dom": "ai",
  "zh": "AMD 82亿美元收购World Labs，李飞飞任首席科学家",
  "en": "AMD 花 82 亿美元买下李飞飞的 World Labs，她直接空降成首席科学家",
  "sum": "AMD宣布以82亿美元股票收购李飞飞创立的World Labs，李飞飞将出任执行副总裁兼首席科学家。",
  "t": "11:12",
  "heat": 9.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://www.oschina.net/news/502790/amd-will-acquire-fei-fei-lis-world-labs-for-8-2-billion"
 },
 {
  "src": "TechCrunch AI",
  "dom": "ai",
  "zh": "英伟达推出管控失控AI代理的新平台",
  "en": "Nvidia launches new platform for reining in rogue AI agents",
  "sum": "黄仁勋发布软硬件工具包，为AI代理增加独立安全层，防止其逃出测试环境。",
  "t": "02:31",
  "heat": 8.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://techcrunch.com/2026/09/28/nvidia-launches-new-platform-for-reining-in-rogue-ai-agents/"
 },
 {
  "src": "TechCrunch AI",
  "dom": "ai",
  "zh": "Anthropic发布Sonnet 5.5模型",
  "en": "Anthropic releases Sonnet 5.5, which it calls a significantly cheaper, faster work partner",
  "sum": "Anthropic推出中端模型Sonnet 5.5，称响应更快、token消耗更低、成本更便宜。",
  "t": "02:00",
  "heat": 8.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://techcrunch.com/2026/09/28/anthropic-releases-sonnet-5-5-which-it-calls-a-significantly-cheaper-faster-work-partner/"
 },
 {
  "src": "TechCrunch AI",
  "dom": "ai",
  "zh": "OpenAI仍难掌控AI失控活动",
  "en": "OpenAI still doesn’t seem to have a handle on all of its rogue AI activity",
  "sum": "OpenAI发布错位报告网站，披露多起AI失控事件，引发担忧。",
  "t": "01:09",
  "heat": 8.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://techcrunch.com/2026/09/28/openai-still-doesnt-seem-to-have-a-handle-on-all-of-its-rogue-ai-activity/"
 },
 {
  "src": "TechCrunch AI",
  "dom": "ai",
  "zh": "Meta推出企业AI平台并聘MongoDB CEO",
  "en": "Meta launches enterprise AI platform, hires MongoDB CEO to lead new initiative",
  "sum": "Meta发布企业AI平台，涵盖Muse等产品，并聘请MongoDB CEO领导新计划。",
  "t": "00:52",
  "heat": 8.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://techcrunch.com/2026/09/28/meta-launches-enterprise-ai-platform-hires-mongodb-ceo-to-lead-new-initiative/"
 },
 {
  "src": "量子位",
  "dom": "ai",
  "zh": "OpenAI因新模型太强叫停发布",
  "en": "",
  "sum": "AGI计划暂停。",
  "t": "15:49",
  "heat": 8.0,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://www.qbitai.com/2026/09/499140.html"
 },
 {
  "src": "InfoQ 中文",
  "dom": "ai",
  "zh": "82 亿美元、全股票交易：AMD 收购 World Labs，李飞飞直接向苏姿丰汇报",
  "en": "",
  "sum": "点击查看原文>",
  "t": "21:00",
  "heat": 8.0,
  "ext": false,
  "chars": 4050,
  "preview": "9 月 29 日早间，AMD 宣布了一笔跨越芯片与前沿模型研究的交易：公司已与李飞飞创办的 World Labs 签署最终收购协议，交易作价约 82 亿美元，全部以 AMD 股票支付。交易预计在 2026 年底前完成，仍须获得监管批准并满足其他交割条件。换言之，双方已经签约，但收购尚未完成。 从 AMD 向美国证券交易",
  "url": "https://www.infoq.cn/article/KaaKQS6x5KiSlHa5UVVz"
 },
 {
  "src": "Solidot",
  "dom": "ai",
  "zh": "Starship 完成首次轨道发射",
  "en": "",
  "sum": "SpaceX 于 9 月 28 日 8:15 a.m. EDT 在德州的 Starbase 发射了其重型火箭 Starship，执行第 14 次飞行任务，也是首次轨道发射，将 26 颗 Starlink V3 卫星送到轨道上。这次发射仍然是测试飞行，SpaceX 未尝试回收火箭，上面级 Ship 4",
  "t": "00:16",
  "heat": 8.0,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://www.solidot.org/story?sid=85497"
 },
 {
  "src": "开源中国",
  "dom": "ai",
  "zh": "Claude Sonnet 5.5发布",
  "en": "Claude Sonnet 5.5 发布：速度快 3 成、Agent 编程评测从 10% 跳到 70%",
  "sum": "Anthropic发布Sonnet 5.5，速度提升30%以上，Agent编程评测从10%跃升至70%。",
  "t": "12:14",
  "heat": 8.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://www.oschina.net/news/502794/claude-sonnet-5-5"
 },
 {
  "src": "Gematsu",
  "dom": "game",
  "zh": "Remothered: Tormented Fathers Remastered and Remothered: Broken Porcelain Remastered launch in Q1 2027",
  "en": "",
  "sum": "Remothered: Tormented Fathers Remastered and Remothered: Broken Porcelain Remastered will launch for PlayStation 5, Xbox …",
  "t": "21:21",
  "heat": 8.0,
  "ext": false,
  "chars": 129,
  "preview": "Remothered: Tormented Fathers Remastered and Remothered: Broken Porcelain Remastered will launch for PlayStation 5, Xbox … Source",
  "url": "https://www.gematsu.com/2026/09/remothered-tormented-fathers-remastered-and-remothered-broken-porcelain-remastered-launch-in-q1-2027"
 },
 {
  "src": "Eurogamer",
  "dom": "game",
  "zh": "Controversy erupts around Ace Combat 8 on PC as bundled Belkan War re-release remains problematically attached to the new game, whereas it's standalone on console",
  "en": "",
  "sum": "Early access to Ace Combat 8: Wings of Theve is now available to owners of the game's Deluxe Edition, but the launch has been soured due to publisher ",
  "t": "21:15",
  "heat": 7.7,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://www.eurogamer.net/ace-combat-8-the-belkan-war-pre-order-bonus-steam-community-reaction"
 },
 {
  "src": "机核",
  "dom": "game",
  "zh": "街区派对战火骤起：《家有恶邻》正式上线 1.0 版本",
  "en": "",
  "sum": "由开发商 Invisible Walls 打造的多人派对乱斗游戏《家有恶邻》（Neighbors: Suburban Warfare），现已以免费游玩的形式登陆 Steam PC、PlayStation 5 与 Xbox Series X|S，并支持跨平台联机。 抡起你的平底锅，戴上拳击手套，郊区霸",
  "t": "22:00",
  "heat": 7.7,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://www.gcores.com/articles/220371"
 },
 {
  "src": "GameSpot",
  "dom": "game",
  "zh": "GTA 5 For Switch Mod Project Shuts Down, Dev Thanks Take-Two For Its “Mercy”",
  "en": "",
  "sum": "The creator of a mod project that sought to bring Rockstar's Grand Theft Auto 5 to Switch is closing up shop, apparently at the request of rights owne",
  "t": "21:07",
  "heat": 7.1,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://www.gamespot.com/articles/gta-5-for-switch-mod-project-shuts-down-dev-thanks-take-two-for-its-mercy/"
 },
 {
  "src": "PC Gamer",
  "dom": "game",
  "zh": "SteelSeries Rival Pro gaming mouse review",
  "en": "",
  "sum": "SteelSeries is back, baby.",
  "t": "22:00",
  "heat": 7.1,
  "ext": false,
  "chars": 725,
  "preview": "<p>Jacob got his hands on a gaming PC for the first time when he was about 12 years old. He swiftly realised the local PC repair store had ripped him off with h",
  "url": "https://www.pcgamer.com/hardware/gaming-mice/steelseries-rival-pro-gaming-mouse-review/"
 },
 {
  "src": "VGC",
  "dom": "game",
  "zh": "CD Projekt says it overhauled Witcher 3 gameplay because it was ‘obviously’ the weakest part",
  "en": "",
  "sum": "CD Projekt Red's Paweł Sasko explains how the team decided what to update",
  "t": "22:28",
  "heat": 7.1,
  "ext": false,
  "chars": 81,
  "preview": "CD Projekt Red's Paweł Sasko explains how the team decided what to update… Source",
  "url": "https://www.videogameschronicle.com/news/cd-projekt-says-it-overhauled-witcher-3-gameplay-because-it-was-obviously-the-weakest-part/"
 },
 {
  "src": "VGC",
  "dom": "game",
  "zh": "Witcher 3 Remastered best console graphics mode: Performance vs Ray Tracing",
  "en": "",
  "sum": "The best console graphics mode to use while playing The Witcher 3: Wild Hunt Remastered on every platform",
  "t": "22:02",
  "heat": 7.1,
  "ext": false,
  "chars": 113,
  "preview": "The best console graphics mode to use while playing The Witcher 3: Wild Hunt Remastered on every platform… Source",
  "url": "https://www.videogameschronicle.com/guide/the-witcher-3-remastered-best-console-graphics-mode-performance-vs-ray-tracing/"
 },
 {
  "src": "VGC",
  "dom": "game",
  "zh": "The Witcher 3: Developers talk remastering a classic and creating Songs of the Past",
  "en": "",
  "sum": "Witcher 3 developers discuss Songs of the Past, the remaster's combat overhaul, and why Dandelion's story deserved more",
  "t": "20:43",
  "heat": 7.1,
  "ext": false,
  "chars": 105,
  "preview": "Witcher 3 developers discuss Songs of the Past, the remaster's combat overhaul, and why Dandelion' Source",
  "url": "https://www.videogameschronicle.com/features/interviews/the-witcher-3-developers-talk-remastering-a-classic-and-creating-songs-of-the-past/"
 },
 {
  "src": "Hacker News",
  "dom": "ai",
  "zh": "Show HN: Jevstiller – Distill Jev into a local model, with a disagreement bound",
  "en": "",
  "sum": "",
  "t": "20:05",
  "heat": 7.1,
  "ext": false,
  "chars": 0,
  "preview": "",
  "url": "https://jevstiller.pages.dev/posts/the-guarantee/"
 },
 {
  "src": "GameSpot",
  "dom": "game",
  "zh": "顽皮狗正开发两个最后生还者新项目",
  "en": "Naughty Dog Is Working On Two New The Last Of Us Projects",
  "sum": "顽皮狗负责人确认工作室正开发两个《最后生还者》新项目，科幻新作2027年全面揭晓。",
  "t": "16:05",
  "heat": 7.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://www.gamespot.com/articles/naughty-dog-is-working-on-two-new-the-last-of-us-projects/"
 },
 {
  "src": "Eurogamer",
  "dom": "game",
  "zh": "全球所有版本《巫师3》今日免费升级重制版",
  "en": "All versions of The Witcher 3 \"that exist in the world\" will be upgraded with the free Remastered edition today",
  "sum": "CDPR确认全球所有版本的《巫师3：狂猎》今日免费升级为重制版。",
  "t": "17:48",
  "heat": 7.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://www.eurogamer.net/all-versions-of-the-witcher-3-that-exist-in-the-world-will-be-upgraded-with-the-free-remastered-edition-today"
 },
 {
  "src": "Eurogamer",
  "dom": "game",
  "zh": "顽皮狗确认还有两个最后生还者项目",
  "en": "Naughty Dog confirms two more The Last of Us projects are in the works, won't show off Intergalactic: The Heretic Prophet until 2027",
  "sum": "顽皮狗确认两个《最后生还者》新项目处于早期开发，星际新作2027年才展示。",
  "t": "16:36",
  "heat": 7.0,
  "ext": true,
  "chars": 0,
  "preview": "",
  "url": "https://www.eurogamer.net/naughty-dog-confirms-two-more-the-last-of-us-projects-are-in-the-works-wont-show-off-intergalactic-the-heretic-prophet-until-2027"
 },
 {
  "src": "VGC",
  "dom": "game",
  "zh": "《巫师3：狂猎》重制版现已上线",
  "en": "The Witcher 3 Wild Hunt Remastered is out now, here’s how to start playing",
  "sum": "《巫师3：狂猎》重制版正式发售，官方给出开始游玩的方法。",
  "t": "18:10",
  "heat": 7.0,
  "ext": true,
  "chars": 74,
  "preview": "How to start playing The Witcher 3: Wild Hunt Remastered right now… Source",
  "url": "https://www.videogameschronicle.com/guide/the-witcher-3-wild-hunt-remastered-is-out-now-heres-how-to-start-playing/"
 }
];
